Add Solr instructions for prebuilt Lucene index
castorini/anserini pull request #1379
Opened 2020-09-11 16:18 UTC by adamyy

* Provides instructions about how to configure Solr to read prebuilt Lucene indexes

2020-09-11 16:38 UTC, lintool requested changes
Minor comments, thanks for the PR!

2020-09-11 16:38 UTC, lintool commented on docs/solrini.md
> +To achieve this, some housekeeping are required. The following uses [robust04](regressions-robust04.md) as an example.
We adopt the convention of each sentence on a line; here and below.
robust04 -> Roboust04

2020-09-11 16:38 UTC, lintool commented on docs/solrini.md
> +Then, either *copy the index files to where Solr expected*, or *tell Solr where to look for*.
Let's be opinionated - pick the better option (my vote is for the first) and do that - don't give the user the choice.

2020-09-11 16:38 UTC, lintool commented on docs/solrini.md
> +Here `robust04` is a Trec collection whose schema is already taken care of by [managed-schema](https://github.com/castorini/anserini/blob/master/src/main/resources/solr/anserini/conf/managed-schema)
Trec -> TREC

2020-09-12 05:10 UTC, adamyy commented
Actually, as I was testing the prebuilt index with `run_solr_integration.py`, I noticed that there are discrepancy between expected and actual trec_eval benchmark. Currently looking into the cause and this PR might not be ready to merge just yet!

2020-09-12 11:30 UTC, adamyy commented
Looked a bit more into this, turns out my index was not built with the `contents` field (only `id` and `raw`) and `SearchSolr` uses `contents` as the default field of search. So it either errors out / produce nonsense output.

I guess it is worth noting that the prebuilt index should have the `contents` field for this to work properly? When we are indexing into Solr using `IndexCollection`, it seems like the `contents` field are created regardless of whether we specify `-storeContents` or not. However, if we are just producing a Lucene index then `contents` field only present if we specify `-storeContents`.

2020-09-12 11:39 UTC, lintool commented
yup, this should be documented somewhere!

2020-09-12 11:42 UTC, lintool commented
Also, check out: https://github.com/castorini/anserini/blob/master/.travis.yml#L20

It _might_ be reasonable to do a complete e2e integration test based on this? I mean, travis is running it all the time... just a matter of moving it inside JUnit?

2020-09-12 13:15 UTC, adamyy commented
Actually, I have misunderstood the issue again. 😅 

I read more about what `stored` means for a Lucene Document Field, and found this [explanation](https://stackoverflow.com/a/4185226). Turns out `stored=false` still makes the field searchable, it is just that the field is not stored as is, and will not be returned as part of the query result.

Then I was wondering, how come `SearchCollection` on non-`storeContents` MSMARCO index can produce the output that matches the regression, but `SearchSolr` cannot?

I noticed [solrconfig.xml#L785](https://github.com/castorini/anserini/blob/master/src/main/resources/solr/anserini/conf/solrconfig.xml#L785) set the default field of search to a field called `_text_` (this is the default Solr config). However, in our case we want it to be `contents`, and it is what we were trying to enforce at [SearchSolr.java#L225](https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/search/SearchSolr.java#L225). My hunch is that Solr internally picks the default field of search based on both query parameters and solrconfig.xml, and it might have picked the wrong one in my previous run.

I modified this field from `_text_` to `contents`, recreated the Solr core with the updated configset and the non-`storeContents` index, then performed `SearchSolr` again. The good news is that the result now matches the regression. I will perform a couple more tests to ensure that this is what is causing the issue.

2020-09-12 13:16 UTC, adamyy commented
> Also, check out: https://github.com/castorini/anserini/blob/master/.travis.yml#L20
> 
> It _might_ be reasonable to do a complete e2e integration test based on this? I mean, travis is running it all the time... just a matter of moving it inside JUnit?

Do we want to do `run_solr_regression.py` in travis? @lintool

2020-09-12 17:50 UTC, adamyy commented
> I modified this field from `_text_` to `contents`, recreated the Solr core with the updated configset and the non-`storeContents` index, then performed `SearchSolr` again. The good news is that the result now matches the regression. I will perform a couple more tests to ensure that this is what is causing the issue.

Big oops, I tested my assumption again with a newly built index (without `-storeContents` flag) everything worked just fine. TL;DR I think my original index was broken. Sorry for causing the confusion! This PR should be ready now! @lintool

2020-09-13 00:47 UTC, lintool commented
> Do we want to do `run_solr_regression.py` in travis? @lintool

Maybe `run_solr_regression.py` with the small CACM collection in travis? Shouldn't be too difficult to do? If you think it's a good idea, create another issue to keep track of progress?

2020-09-13 00:47 UTC, lintool approved these changes

2020-09-13 00:47 UTC, merged