Add Indexing Collection and Generator for Epidemic QA Dataset
castorini/anserini pull request #1393
Opened 2020-10-19 00:19 UTC by justinborromeo

The Epidemic QA task (https://bionlp.nlm.nih.gov/epic_qa/) uses a modified version of the CORD-19 dataset.  This PR adds Collection and Generator classes for the dataset.  The dataset comprises an `info.txt` file which contains a list of JSON documents.  The schema of the JSON documents is defined at https://bionlp.nlm.nih.gov/epic_qa/#doc-schema.

The code was validated by:
1. Adding a unit test for the EpidemicQACollection class.
2. Running the indexing task
```
sh target/appassembler/bin/IndexCollection -collection EpidemicQAC
ollection -generator EpidemicQAGenerator -threads 8 -input collections/epic_qa_cord_2020-06-19_v2 -index indexes/lucene-index-epidemic-qa -storePositions -storeDocvectors -storeContents -storeRaw -optimize > logs/logs.epidemic-qa.txt
```

3. Using Pyserini's SimpleSearcher to search the generated index (https://gist.github.com/justinborromeo/74a2fb7ca143fedf9ecf9c881f95db16) and checking if the returned documents were relevant to the query.

2020-10-19 12:16 UTC, ronakice commented
@justinborromeo does this work for the consumer task too?

2020-10-19 17:25 UTC, justinborromeo commented
@ronakice I'll test it tonight but it should work since it's the same format.

2020-10-19 17:29 UTC, lintool requested changes
minor nits. please tweak and I'll merge.

2020-10-19 17:29 UTC, lintool commented on src/main/java/io/anserini/index/generator/EpidemicQAGenerator.java
> +  {
braces with preceding line.

2020-10-19 17:29 UTC, lintool commented on src/test/java/io/anserini/collection/EpidemicQACollectionTest.java
> +{
same

2020-11-01 18:48 UTC, justinborromeo commented
Ready for review again.

2020-11-06 20:41 UTC, merged