Dynamic type support for ParquetDenseVectorDocumentGenerator
castorini/anserini pull request #2667
Opened 2024-12-22 00:44 UTC by b8zhong

To solve issue https://github.com/castorini/anserini/issues/2662

Not done (nor do I have tests yet!). But let me know what you think of this @lintool

2024-12-22 11:11 UTC, lintool commented
No, I don't think you're doing it at the best place... I was thinking in `ParquetDenseVectorCollection` somewhere here:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/collection/ParquetDenseVectorCollection.java#L166

i.e., at the point you're reading in the data from the file.

2024-12-23 02:18 UTC, b8zhong commented
Ohh - got it that makes sense. Will update

2024-12-25 20:20 UTC, lintool commented
We have a test failure here?

We currently have `src/test/resources/sample_docs/parquet/msmarco-passage-bge-base-en-v1.5.parquet` - what about a test cases where we have a variant of the parquet file stored as floats, and we make sure both work?

2024-12-27 04:32 UTC, vincent-4 commented
Updated the test format to use the same structure as previously– (in the two files below)
With new entries in:
```
src/test/java/io/anserini/index/IndexFlatDenseVectorsTest.java
src/test/java/io/anserini/index/IndexHnswDenseVectorsTest.java
```


And added a new, converted parquet file (floats) in the path (used by the new tests): ```src/test/resources/sample_docs/parquet/msmarco-passage-bge-base-en-v1.5.parquet-float/test1.parquet```

2025-01-01 20:44 UTC, lintool requested changes
Thoughts?

2025-01-01 20:44 UTC, lintool commented on src/main/java/io/anserini/collection/ParquetDenseVectorCollection.java
> +        vector[i] = isDouble ? (float) listGroup.getDouble("element", 0) : listGroup.getFloat("element", 0);
Here, you're assuming if it's not a double, it's a float, right? But what if it's an int or some other type?

How about we check explicitly for double and float, and throw an exception if it's neither?

2025-01-03 16:03 UTC, lintool approved these changes

2025-01-03 16:03 UTC, merged