Prune Parquet Dependencies
castorini/anserini pull request #2668
Opened 2024-12-24 14:24 UTC by vincent-4

Pruned with https://github.com/strategicblue/parquet-floor, as well as added tests.

2024-12-24 14:47 UTC, lintool requested changes
Nice!

What's the fatjar size, before and after?

2024-12-24 14:47 UTC, lintool commented on pom.xml
> +      <id>strategicblue</id>
I don't think we need this?
The artifact is published in Maven central:
https://central.sonatype.com/artifact/blue.strategic.parquet/parquet-floor

2024-12-24 14:47 UTC, lintool commented on src/test/java/io/anserini/collection/ParquetDenseVectorCollectionTest.java
> +public class ParquetDenseVectorCollectionTest extends DocumentCollectionTest<ParquetDenseVectorCollection.Document> {
Move "Tests for the ParquetDenseVectorCollection class...." comment here.

2024-12-24 14:47 UTC, lintool commented on src/test/java/io/anserini/collection/ParquetDenseVectorCollectionTest.java
> +package io.anserini.collection;
Add standard Apache 2 license boilerplate.

2024-12-24 18:24 UTC, vincent-4 commented
@lintool
See [3e85803](https://github.com/castorini/anserini/pull/2668/commits/3e858036a866c2bef5e96276056f69c61b695453) for the changes that address your feedback. I updated the Parquet format to version 1.49 in the same commit, but it caused issues. [d17afc8](https://github.com/castorini/anserini/pull/2668/commits/d17afc89b10ff9f7c67408c99b5854be2dbd121a) resolves this problem.

2024-12-24 19:52 UTC, lintool commented
🎉 Yay for smaller size!

```
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
```
Do we still need this though?

2024-12-24 20:01 UTC, vincent-4 commented
I keep the jitpack.io repository as it's required for com.github.TREMA-UNH:trec-car-tools-java dependency.
See: https://github.com/TREMA-UNH/trec-car-tools-java/blob/master/pom.xml#L14-L16 
If I'm not wrong? I don't find it on Maven central.

2024-12-24 20:11 UTC, lintool commented
Ah, okay! I'll queue this up for regression testing (machines occupied right now) before I merge.

What tests have you run, BTW? Did the MS MARCO v1 tests pass?

2024-12-26 02:11 UTC, lintool commented
Need to run more regressions, but initial signs are 👍 - the following passed:

```
python src/main/python/run_regression.py --download --index --verify --search --regression msmarco-v1-passage.bge-base-en-v1.5.parquet.flat.onnx
```

2024-12-27 18:49 UTC, vincent-4 commented
Any updates on the regressions?

2025-01-02 12:28 UTC, lintool commented
@vincent-4 why are we on v1.36 and not a later version?

2025-01-02 19:03 UTC, vincent-4 commented
> @vincent-4 why are we on v1.36 and not a later version?

Without modifying the existing codebase, I tested `parquet-floor` versions between 1.36 and 1.49. The latest version that doesn't produce upgrade-related errors using `mvn clean verify` is 1.36.

I have two possible options:

1. Continue working on fixing the (several) errors related to switching to the latest version of `parquet-floor` (which would require more changes).
2. Implement all the changes now if your priority is just to use parquet-floor, which should be fine given the successful regressions and MSMARCO tests. If we choose this option, I could try upgrading to the latest version in another PR.

Let me know which approach you prefer?

2025-01-03 16:01 UTC, lintool commented
I ran all Parquet regressions:

```bash
cat src/main/python/regressions-batch0* | grep parquet > src/main/python/regressions-parquet.txt
nohup python src/main/python/run_regressions_with_load.py --file src/main/python/regressions-parquet.txt --load 64 --sleep 60 >& regressions.parquet.log &
```

Everything checks out. Ready to merge.

2025-01-03 16:02 UTC, lintool approved these changes

2025-01-03 16:02 UTC, merged